name: contact_demo2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.9
  flutter_phone_direct_caller: ^2.0.0
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  neon: ^0.1.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  flutter_native_splash: ^2.2.8
  flutter_launcher_icons: ^0.13.1
  splashscreen:
    git: https://github.com/gautam7-github/SplashScreenFlutterPackage.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/data.json
    - assets/skctpng.png
    - assets/welcome-one.png
    - assets/background.png
    - assets/google_icon.png
    - assets/skct_app_icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          style: italic
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Bold.ttf



flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/skctpng.png
  image_dark: assets/skctpng.png
  branding_dark: assets/skctpng.png

  android_12:
    color:  "#ffffff"
    color_dark: "#ffffff"
    branding: assets/skctpng.png
    image_dark: assets/skctpng.png
    image: assets/skctpng.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/skct_app_icon.png"
  min_sdk_android: 21