name: contact_demo2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.9
  flutter_phone_direct_caller: ^2.0.0
  cloud_firestore: ^3.4.6
  firebase_core: ^1.21.1
  firebase_database: ^9.1.3
  neon: ^0.1.0
  firebase_auth: ^3.7.0
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  flutter_native_splash: ^2.2.8
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data.json
    - assets/skctpng.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          style: italic


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/skctpng.png
  image_dark: assets/skctpng.png
  branding_dark: assets/skctpng.png

  android_12:
    color:  "#ffffff"
    color_dark: "#ffffff"
    branding: assets/skctpng.png
    image_dark: assets/skctpng.png
    image: assets/skctpng.png